In [1]:
# in Step 1, we query the original knowledge graph in SAP HANA to extract all triples related to Ukraine

import os
from dotenv import load_dotenv
load_dotenv()
from hdbcli import dbapi

# HANA Credentials
address = os.getenv("HANA_HOST")
port = os.getenv("HANA_PORT")
user = os.getenv("HANA_USER")
password = os.getenv("HANA_PASSWORD")

connection = dbapi.connect(address=address, port=port, user=user, password=password)
cursor = connection.cursor()

graph_query = """
SELECT * FROM SPARQL_TABLE('
  SELECT ?s ?p ?o 
  WHERE { GRAPH <ukraine_knowledgegraph> { ?s ?p ?o . } }
');
"""

cursor.execute(graph_query)
graph_rows = cursor.fetchall()

cursor.close()
connection.close()

import pandas as pd
graph_df = pd.DataFrame(graph_rows, columns=['subject', 'predicate', 'object'])

graph_df.to_dict(orient='records')

  subject                                        predicate   object
0      C1  http://www.w3.org/1999/02/22-rdf-syntax-ns#type  Country
1      C2  http://www.w3.org/1999/02/22-rdf-syntax-ns#type  Country
2      C1                                             name  Ukraine
3      C2                                             name   Russia

In [6]:
str(graph_rows)

"[('C1', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'Country'), ('C2', 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type', 'Country'), ('C1', 'name', 'Ukraine'), ('C2', 'name', 'Russia')]"

In [9]:
# In step 2, we get the summary of the latest developments regarding the war in Ukraine

import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# First API call: Initialize data
initialize_url = 'https://geopolitics_api.cfapps.ap10.hana.ondemand.com/initialize-data/'
headers = {'accept': 'application/json'}

initialize_response = requests.get(initialize_url, headers=headers, verify=False)
print(f"Initialize status: {initialize_response.status_code}")

# Second API call: Get geopolitics prompt
prompt_url = 'https://geopolitics_api.cfapps.ap10.hana.ondemand.com/geopolitics_prompt/'
headers = {
    'accept': 'application/json',
    'Content-Type': 'application/json'
}
data = {'prompt': ''}

prompt_response = requests.post(prompt_url, headers=headers, json=data, verify=False)
summary_output = prompt_response.text

summary_output

Initialize status: 200

'"Bottom line\\n- Russia is pressing along the Donetsk axis toward Pokrovsk with localized gains and heavy attrition, while Ukraine’s long‑range strikes continue to degrade Russian logistics and fuel infrastructure. Winter weather is slowing tempo but favoring small‑unit infiltration and drone‑centric warfare. Moscow is amplifying a “long‑war, inevitable victory” narrative to shape prospective talks on its terms; negotiation chatter is rising in Europe and the US, but Russian officials still signal no willingness to compromise.\\n\\nOperational picture\\n- Donetsk (Pokrovsk sector): Confirmed Russian advances in Rodynske and along the T‑0504 near Rivne; reports indicate Ukrainian withdrawals from Lysivka and Sukhyi Yar. Russian infiltrations persist toward Myrnohrad and Pokrovsk. Russia claims it “liberated” Pokrovsk and is fighting in Myrnohrad; this is unconfirmed and likely exaggerated. Expect urban fighting risk and continued attritional assaults.\\n- Lyman–Siversk: High‑intensity Russian assaults with fog aiding small‑group infiltrations. Dense drone “kill zones” are complicating Ukrainian logistics. Ukraine reportedly struck Russian ammo/fuel depots deep in occupied Luhansk.\\n- Kharkiv border area: Russian attacks near Vovchansk/Lyptsi aim to fix Ukrainian forces; Ukraine reports Russia lacks forces for a rapid breakthrough. Russian units near Starytsia/Vovchansk face supply shortfalls and heavy losses.\\n- Kupyansk–Borova: Heavy fighting with unconfirmed Russian claims (e.g., Pishchane). Russia advanced west of Novovodyane; continued attacks on multiple villages along the Oskil–Zherebets line.\\n- Zaporizhia: Continued Russian assaults; MoD claims Novodanylivka seized are unconfirmed. Russian guided bomb strikes injured civilians in Zaporizhzhia City and Vilnyansk.\\n- Kherson: Limited Russian ground attacks east of Kherson City; no significant change.\\n- Ukrainian deep strikes: Kyiv claims a Dec 5 drone strike destroyed roughly 70% of Temryuk port capacity (Krasnodar Krai). If validated, this would hit Russian logistics and oil handling in the Black Sea area.\\n- Air/drone campaign: Russia launched about 149 drones overnight Dec 7–8; Ukraine downed 131 (~88% intercept rate). Strikes caused power outages across several oblasts. Sustained tempo is straining Ukrainian air defenses.\\n\\nInformation and political warfare\\n- Kremlin narrative: Putin is touting economic resilience (2025 GDP +1%, inflation ~6%) and pro‑natalist policies to signal endurance. ISW assesses the economy is under more strain than admitted and that messaging is aimed at shaping US‑Russia talks and pressuring Kyiv/West toward concessions.\\n- No compromise posture: Senior Russian officials again framed objectives as Ukrainian “capitulation,” with talk of “silent” negotiations likely masking rejection of substantive proposals.\\n- Planned provocations: Russia is reportedly recruiting women, especially mothers of POW/MIA, to stage “peaceful protests” in occupied southern/eastern cities to push the false narrative that Kyiv is illegitimate—potentially laying groundwork to contest any future deal.\\n\\nEuropean/Transatlantic context (salient open‑source signals)\\n- Negotiations discourse is intensifying (high media volume of consult/negotiation events). EU officials are floating independent peace concepts while NATO seeks a seat at any talks. Ukraine is signaling concern about being sidelined.\\n- EU reportedly agreed to ban Russian gas imports, increasing long‑term pressure on Russia and necessitating enforcement against circumvention. European defense industrial measures are expanding (e.g., Canada joining a large EU defense scheme), but frictions persist over regulation and market access. Russian arms makers appear to be adapting despite sanctions, underscoring enforcement gaps.\\n- Heightened European focus on counter‑UAS and maritime/undersea security (e.g., UK anti‑submarine tech; French navy engagement of drones near a nuclear submarine base; new German counter‑drone police unit).\\n\\nImplications for NATO\\n- Air and missile defense: Ukraine’s high intercept rates against mass drone waves require sustained resupply of interceptors and cheaper layered C‑UAS solutions, plus electronic warfare and decoys. European infrastructure hardening and rapid repair capacity should be expanded to mitigate grid strikes.\\n- Support to deep strike and ISR: Enabling Ukrainian long‑range precision strike and targeting (ports, depots, rail nodes, fuel storage) is degrading Russian operational reach; continued ISR, strike enablers, and battle damage assessment are critical.\\n- Ground combat enablers: Prioritize thermal/night optics, small UAS, counter‑battery radars, artillery ammunition, mine breaching/engineering, tracked logistics and mobility kits for mud conditions, and casualty evacuation assets.\\n- Information defense: Pre‑bunk and expose staged protest operations; coordinate strategic communications to deny Russian narratives of Kyiv’s illegitimacy and inevitable Russian victory.\\n- Maritime/undersea security: Increase monitoring and protection of Black Sea and European undersea infrastructure; integrate emerging UK/EU ASW capabilities.\\n- Policy cohesion: Align on negotiation parameters to prevent Russian wedge strategies; ensure Ukraine’s central role in any talks. Tighten and enforce sanctions (including energy and shipping) to close loopholes.\\n\\nNear‑term watch items\\n- Ground truth in Pokrovsk–Myrnohrad: independent corroboration of control lines, patterns of urban fires, and civilian evacuation flows.\\n- Effects of the Temryuk strike: indications of fuel or logistics disruptions in Krasnodar/occupied territories and rerouting of maritime supply.\\n- Russian force generation and sustainment: rotation tempo, use of ATVs/light vehicles in poor weather, and casualty replacement rates around Vovchansk and Pokrovsk.\\n- Drone campaign dynamics: mix of Shaheds/domestic UAVs, Ukraine’s interceptor expenditure rates, and adaptation in Russian targeting of energy infrastructure.\\n- Information operations: emergence of “protest” footage/narratives from occupied cities; shifts in Kremlin messaging about talks.\\n- Diplomatic signals: concrete EU/US peace proposals, Russian preconditions, and NATO’s role in any framework.\\n\\nProbable scenarios (next 90–120 days)\\n- Baseline: Continued grinding Russian advances around Pokrovsk with localized gains elsewhere; Ukraine holds major defensive belts; sustained drone and glide‑bomb campaigns; no decisive front collapse.\\n- Adverse: Russian breakthrough in the Pokrovsk–Myrnohrad urban area creating pressure toward Kostyantynivka–Druzhkivka; intensified strikes causing prolonged Ukrainian power outages; increased external pressure for talks on unfavorable terms.\\n- Opportunity: Ukrainian deep‑strike campaign forces Russian operational pause via logistics disruption; improved C‑UAS reduces impact of drone waves; Western deliveries stabilize Ukrainian air defense and artillery resupply, enabling local counterattacks.\\n\\nConfidence notes\\n- Russian claims of capturing Pokrovsk are unconfirmed and likely part of information operations. Treat with caution pending independent verification.\\n- The reported 70% degradation of Temryuk port requires additional battle damage assessment to confirm scale and operational impact."'

In [2]:
# Package everything as functions

import os
from dotenv import load_dotenv
load_dotenv()
from hdbcli import dbapi

def get_ua_knowledgegraph():
    """Get the knowledge graph related to Ukraine from SAP HANA."""
    # HANA Credentials
    address = os.getenv("HANA_HOST")
    port = os.getenv("HANA_PORT")
    user = os.getenv("HANA_USER")
    password = os.getenv("HANA_PASSWORD")

    connection = dbapi.connect(address=address, port=port, user=user, password=password)
    cursor = connection.cursor()

    graph_query = """
    SELECT * FROM SPARQL_TABLE('
    SELECT ?s ?p ?o 
    WHERE { GRAPH <ukraine_knowledgegraph> { ?s ?p ?o . } }
    ');
    """

    cursor.execute(graph_query)
    graph_rows = cursor.fetchall()

    cursor.close()
    connection.close()

    return graph_rows

import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def get_latest_summary():

    # First API call: Initialize data
    initialize_url = 'https://geopolitics_api.cfapps.ap10.hana.ondemand.com/initialize-data/'
    headers = {'accept': 'application/json'}

    initialize_response = requests.get(initialize_url, headers=headers, verify=False)
    print(f"Initialize status: {initialize_response.status_code}")

    # Second API call: Get geopolitics prompt
    prompt_url = 'https://geopolitics_api.cfapps.ap10.hana.ondemand.com/geopolitics_prompt/'
    headers = {
        'accept': 'application/json',
        'Content-Type': 'application/json'
    }
    data = {'prompt': ''}

    prompt_response = requests.post(prompt_url, headers=headers, json=data, verify=False)
    summary_output = prompt_response.text

    return summary_output

In [3]:
# In step 3, we use GPT-5 to generate the SPARQL notation to update the knowledge graph

from datetime import date

AICORE_CLIENT_ID = os.getenv("AICORE_CLIENT_ID")
AICORE_CLIENT_SECRET = os.getenv("AICORE_CLIENT_SECRET")
AICORE_AUTH_URL = os.getenv("AICORE_AUTH_URL")
AICORE_BASE_URL = os.getenv("AICORE_BASE_URL")
AICORE_RESOURCE_GROUP = os.getenv("AICORE_RESOURCE_GROUP")
os.environ['AICORE_CLIENT_ID'] = AICORE_CLIENT_ID
os.environ['AICORE_CLIENT_SECRET'] = AICORE_CLIENT_SECRET
os.environ['AICORE_AUTH_URL'] = AICORE_AUTH_URL
os.environ['AICORE_BASE_URL'] = AICORE_BASE_URL
os.environ['AICORE_RESOURCE_GROUP'] = AICORE_RESOURCE_GROUP

from gen_ai_hub.proxy.native.openai import chat

def sparql_prompt(summary, graph):
    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": f"You are a geopolitical analyst and an ontology expert proficient in SPARQL notation tasked with extracting subject-predicate-object (SPO) triples from documents about the war in Ukraine." +
                            f"Here is the document for processing regarding the war in Ukraine: {summary}" +
                            f"Here is the existing knowledge graph about the war in Ukraine: {str(graph)}" +
                            f"Find all the SPO triples resulting from the document and draft a SPARQL notation that adds all the new SPO triples to the knowledge graph." +
                            f"Return ONLY the pure SPARQL INSERT DATA statement, like this example:" +
                            ' INSERT DATA { GRAPH <ukraine_knowledgegraph> { <C1> a <Country>; <name> "Ukraine". <C2> a <Country>; <name> "Russia". }} ' +
                            f"CRITICAL: Use regular double quotes for string literals in SPARQL. Do NOT use backslashes. Do NOT escape quotes with backslash." +
                            f"Return ONLY the SPARQL INSERT DATA statement on a single line. No wrapper, no backslashes, no line breaks." +
                            f"One more thing: For SPO triples that might be temporally sensitive, ensure to include appropriate temporal qualifiers (e.g., today's date, which is: {str(date.today())})."
                }
            ]
        }
    ]
    return messages

def write_prompt_messages(messages, model_name = "gpt-5"): # Models can be changed here
    """Send messages to the model and return the response."""
    kwargs = dict(model_name=model_name, messages=messages)
    response = chat.completions.create(**kwargs)
    return response.to_dict()["choices"][0]["message"]["content"]

def get_sparql(summary, graph):
    """Get response from GPT 5."""
    messages = sparql_prompt(summary, graph)
    answer_entities = write_prompt_messages(messages)
    return answer_entities

In [ ]:
# In step 4, we update the knowledge graph in SAP HANA with the generated SPARQL notation

def update_knowledge_graph(sparql_notation):
    """Update the knowledge graph in SAP HANA."""
    # HANA Credentials
    address = os.getenv("HANA_HOST")
    port = os.getenv("HANA_PORT")
    user = os.getenv("HANA_USER")
    password = os.getenv("HANA_PASSWORD")

    connection = dbapi.connect(address=address, port=port, user=user, password=password)
    cursor = connection.cursor()

    try:
        # Clean up the SPARQL notation if needed
        if "CALL SPARQL_EXECUTE" in sparql_notation:
            # Extract just the SPARQL INSERT statement from inside the CALL
            start = sparql_notation.find("'") + 1
            end = sparql_notation.rfind("'", 0, sparql_notation.rfind("'"))
            sparql_insert = sparql_notation[start:end]
            
            # Escape single quotes for SQL by doubling them
            sparql_insert_escaped = sparql_insert.replace("'", "''")
            
            # Use SPARQL_EXECUTE with proper parameters
            query = f"CALL SPARQL_EXECUTE('{sparql_insert_escaped}', '', ?, ?)"
            cursor.execute(query)
        else:
            # If it's already a clean SPARQL statement, execute directly
            cursor.execute(sparql_notation)
        
        connection.commit()
        print("Knowledge graph updated successfully!")
        
    except Exception as e:
        print(f"Error updating knowledge graph: {e}")
        print(f"SPARQL statement preview: {sparql_notation[:500]}...")
        connection.rollback()
    finally:
        cursor.close()
        connection.close()

Error updating knowledge graph: (129, "transaction rolled back by an internal error: generic. Error - at line 1 column 85 near '\\': Syntax error - syntax error")
SPARQL statement preview: "CALL SPARQL_EXECUTE(' INSERT DATA { GRAPH <ukraine_knowledgegraph> { <AxisPokrovsk> a <FrontArc>; <name> \"Pokrovsk axis\"; <locatedIn> <RegionDonetsk>. <RegionDonetsk> a <Region>; <name> \"Donetsk Oblast\"; <locatedIn> <C1>. <L19> a <Settlement>; <name> \"Starytsia\"; <locatedIn> <C1>. <L20> a <Settlement>; <name> \"Hulyaipole\"; <locatedIn> <C1>. <L21> a <City>; <name> \"Cheboksary\"; <locatedIn> <C2>. <L24> a <City>; <name> \"Kupyansk\"; <locatedIn> <C1>. <L25> a <Settlement>; <name> \"Borov...

In [4]:
# Test the functions

graph_rows = get_ua_knowledgegraph()
summary_output = get_latest_summary()
sparql_notation = get_sparql(summary_output, graph_rows)
print(sparql_notation)

Initialize status: 200
INSERT DATA { GRAPH <ukraine_knowledgegraph> { <Kostyantynivka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Kostyantynivka". <Druzhkivka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Druzhkivka". <Stepnohirsk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Stepnohirsk". <Hulyaipole> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Hulyaipole". <Stepove> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Stepove". <Oleksandrivka> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Oleksandrivka". <Dnipropetrovsk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Dnipropetrovsk". <Cheboksary> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Cheboksary". <Luhansk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Luhansk". <Donetsk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Donetsk". <Chasiv_Yar> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Location"; <name> "Chasiv Yar". <Donetsk_Drone_Depot> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Infrastructure"; <name> "Donetsk drone depot". <Luhansk_Substation> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Infrastructure"; <name> "Luhansk substation". <Cheboksary_Defense_Site> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Infrastructure"; <name> "Cheboksary defense-industrial site". <DTEK> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Organization"; <name> "DTEK". <DTEK_Last_Coal_Mine_Donetsk> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Infrastructure"; <name> "DTEK last coal mine (Donetsk Oblast)". <Donetsk_Fortress_Belt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Infrastructure"; <name> "Donetsk Fortress Belt". <Zelensky> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Person"; <name> "Volodymyr Zelenskyy". <E94> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Russia"; <locations> "Kostyantynivka"; <locations> "Druzhkivka"; <locations> "Pokrovsk"; <locations> "Myrnohrad"; <finding> "Pressure highest around the Kostyantynivka–Druzhkivka–Pokrovsk axis"; <finding> "Russian gains northwest of Pokrovsk"; <finding> "Heavy use of glide bombs against Myrnohrad"; <weapon> "Glide_Bombs". <E95> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Russia"; <locations> "Lyman"; <locations> "Siversk"; <finding> "Limited Russian gains near Lyman and mixed claims around Siversk". <E96> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Russia"; <locations> "Stepnohirsk"; <finding> "Confirmed Russian advance at Stepnohirsk (western Zaporizhia)". <E97> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Russia"; <locations> "Hulyaipole"; <status> "unconfirmed"; <finding> "Unconfirmed Russian gains near Hulyaipole". <E98> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Ukraine"; <locations> "Stepove"; <locations> "Oleksandrivka"; <finding> "Ukraine advanced near Stepove (Oleksandrivka direction)". <E99> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Battle_Update"; <date> "2025-12-10"; <actor> "Russia"; <locations> "Kherson_City"; <method> "small-boat crossings under fog"; <constraints> "fog". <E100> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Strike_Cycle"; <date> "2025-12-10"; <actor> "Russia"; <method> "launched 110 Shahed-type drones overnight"; <result> "Ukraine downed 84"; <impacts> "hits on energy and civilian sites in Sumy, Kharkiv, and Dnipropetrovsk"; <weapon> "Shahed"; <locations> "Sumy"; <locations> "Kharkiv"; <locations> "Dnipropetrovsk". <E101> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Strike"; <date> "2025-12-10"; <actor> "Ukraine"; <locations> "Cheboksary"; <locations> "Luhansk"; <locations> "Donetsk"; <target> "Cheboksary_Defense_Site"; <target> "Luhansk_Substation"; <target> "Donetsk_Drone_Depot"; <finding> "Ukraine struck a defense-industrial site in Cheboksary, a Luhansk substation, and a Donetsk drone depot". <E102> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Industrial_Update"; <date> "2025-12-10"; <actor> "DTEK"; <locations> "Donetsk"; <finding> "DTEK halted its last coal mine in Donetsk Oblast due to security/power issues"; <status> "halted"; <cause> "security/power issues". <E103> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Operational_Assessment"; <date> "2025-12-10"; <actor> "Russia"; <area_gained_km2> "4669"; <area_percent> "0.77"; <casualties_total> "391270"; <casualties_per_km2> "83"; <finding> "Volunteer recruitment based on financial incentives is hitting diminishing returns and burdening the economy"; <finding> "Sustaining replacements likely requires compulsory reserve mobilization". <E104> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Policy_Move"; <date> "2025-12-10"; <actor> "Russia"; <action> "Dec 8 decree enables compulsory call-ups of inactive reservists for military assemblies in 2026". <E105> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Policy_Reform"; <date> "2025-12-10"; <actor> "Russia"; <action> "Enable year-round conscription processing"; <intent> "planned rolling mobilization without a politically costly mass call-up". <E106> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Negotiation_Assessment"; <date> "2025-12-10"; <actor> "Moscow"; <aim> "seek via talks what it cannot currently achieve militarily including a NATO veto, a puppet government in Kyiv, and limits on Ukraine’s defense"; <demand> "all of Luhansk and Donetsk"; <risk> "could later renege by deeming Ukraine’s leadership illegitimate". <E107> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Diplomatic_Move"; <date> "2025-12-10"; <actor> "US"; <proposal_points> "20"; <quoted_by> "Zelensky"; <status> "territorial issues remain unresolved"; <position_of> "Ukraine"; <position> "Kyiv will not cede land". <E108> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Diplomatic_Position"; <date> "2025-12-10"; <actor> "EU"; <emphasizes> "territorial integrity"; <emphasizes> "ceasefire"; <emphasizes> "security guarantees"; <role_note> "strong European role". <E109> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Indicator"; <date> "2025-12-10"; <indicator_source> "Global media data"; <finding> "spike in consult/negotiation events consistent with an intensifying diplomatic phase". <E110> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Defense_Posture"; <date> "2025-12-10"; <actor> "Europe"; <action> "increasing counter-drone, ASW, and network resilience efforts". <E113> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Claim"; <date> "2025-12-10"; <actor> "TASS"; <claim> "Ukrainian pullbacks near Chasiv Yar"; <status> "unconfirmed"; <narrative> "aligns with Moscow’s narrative of momentum"; <locations> "Chasiv_Yar". <E114> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <finding> "Expect a prolonged attritional campaign with localized Russian gains, heavy glide-bomb use, and persistent drone/missile attacks on energy and logistics". <E115> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Risk_Assessment"; <date> "2025-12-10"; <finding> "Russia’s cognitive operations aim to fracture Western unity and lock in gains via negotiations; any deal lacking enforceable guarantees risks a rapid Russian breakout later". <E116> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <finding> "Ukraine’s deep strikes on Russian defense industry will continue; Russia will disperse and harden key sites". <E117> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <finding> "Drone threats to European infrastructure are rising, reflected in multiple EU member responses". <E118> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Operational_Outlook"; <date> "2025-12-10"; <priority> "Concrete steps toward Russian reservist assemblies and administrative mobilization mechanics"; <priority> "Battlefield pressure around Pokrovsk, Stepnohirsk, and river crossings in Kherson"; <priority> "Indications of glide-bomb stockpiles and delivery capacity"; <priority> "Ukrainian air defense performance against large swarms"; <priority> "Effects on energy infrastructure and hydrology (e.g., dam strikes)"; <priority> "Diplomatic tracks: details of the US 20-point proposal, EU involvement, any floated territorial swaps"; <note> "Kyiv rejects ceding land". <E119> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <scenario> "Negotiated pause"; <finding> "Russia attempts to freeze lines and rearm; high risk of later treaty violation absent robust guarantees and verification"; <recommendation> "NATO should secure durable security architectures for Ukraine and maintain sanctions enforcement". <E120> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <scenario> "Extended attrition (2025–2027)"; <finding> "Russia implements rolling mobilization and aims to grind through Donetsk’s Fortress Belt over 2–3 years; Ukraine holds with continued Western materiel; European defense autonomy grows". <E121> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <scenario> "Localized Russian breakthrough"; <finding> "Most likely near Pokrovsk or western Zaporizhia, enabled by glide bombs and infantry"; <recommendation> "Prepare contingency support packages (ISR, EW, air defense, precision fires)". <E122> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Outlook"; <date> "2025-12-10"; <scenario> "Escalatory strike campaign"; <finding> "Intensified Russian drone/missile attacks on energy, dams, and logistics; increased cross-border UAV incidents in Europe"; <recommendation> "Layered C-UAS, EW, and civil protection upgrades". <E123> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Recommendation"; <date> "2025-12-10"; <actor> "NATO"; <priority> "Bolster Ukraine’s layered air defense and counter-UAS/EW against swarms and glide bombs; expand decoys, camouflage, and rapid repair capacity for energy/logistics"; <priority> "Sustain precision fires, ISR, and counter-battery; support mine breaching and protected mobility to recover maneuver options"; <priority> "Enhance information operations to counter Russia’s inevitability narrative; protect alliance cohesion in a negotiation-heavy media environment"; <priority> "Accelerate European industrial output for munitions and air defenses; coordinate ASW and counter-drone measures across the Baltic and Black Sea regions". <E124> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Information_Operation"; <date> "2025-12-10"; <actor> "Moscow"; <narrative> "intensifying a cognitive warfare push to frame Russian victory as inevitable and the economy as resilient"; <aim> "force concessions at the negotiating table it cannot secure militarily". <E125> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> "Claim"; <date> "2025-12-10"; <actor> "Senior_Russian_Officials"; <claim> "overstate battlefield gains and imply Ukraine’s imminent collapse"; <assessment> "current ground realities do not support this". }}

In [8]:
# In step 4, we update the knowledge graph in SAP HANA with the generated SPARQL notation

def update_knowledge_graph(sparql_notation):
    """Update the knowledge graph in SAP HANA."""
    # HANA Credentials
    address = os.getenv("HANA_HOST")
    port = os.getenv("HANA_PORT")
    user = os.getenv("HANA_USER")
    password = os.getenv("HANA_PASSWORD")

    connection = dbapi.connect(address=address, port=port, user=user, password=password)
    cursor = connection.cursor()

    try:
        # First, drop the existing graph
        drop_query = """
                    CALL SPARQL_EXECUTE('
                    DROP GRAPH <ukraine_knowledgegraph> 
                    ', '', ?, ?);
                    """
        cursor.execute(drop_query)
        connection.commit()
        print("Existing graph dropped")
        
        # Extract clean SPARQL if wrapped in CALL
        if "CALL SPARQL_EXECUTE" in sparql_notation:
            start = sparql_notation.find("'") + 1
            end = sparql_notation.rfind("'", 0, sparql_notation.rfind("'"))
            sparql_insert = sparql_notation[start:end]
        else:
            sparql_insert = sparql_notation.strip()
        
        # Clean up any backslash escaping from GPT
        sparql_insert = sparql_insert.replace('\\"', '"').replace('\\', '')
        
        print(f"Executing SPARQL ({len(sparql_insert)} chars)")
        
        # Use the exact format that works
        query = f"""
                CALL SPARQL_EXECUTE(
                    '{sparql_insert.replace("'", "''")}', 
                    '', 
                    ?, 
                    ?
                );
                """
        cursor.execute(query)
        connection.commit()
        print("Knowledge graph updated successfully!")
        
    except Exception as e:
        print(f"Execution failed: {e}")
        connection.rollback()
    finally:
        cursor.close()
        connection.close()

update_knowledge_graph(sparql_notation)

Existing graph dropped
Executing SPARQL (11333 chars)
Knowledge graph updated successfully!
Knowledge graph updated successfully!

---

## LLM Integration

In [35]:
# in Step 1, we query the original knowledge graph in SAP HANA to extract all triples related to Ukraine (replicating earlier steps)

import os
from dotenv import load_dotenv
load_dotenv()
from hdbcli import dbapi

# HANA Credentials
address = os.getenv("HANA_HOST")
port = os.getenv("HANA_PORT")
user = os.getenv("HANA_USER")
password = os.getenv("HANA_PASSWORD")

connection = dbapi.connect(address=address, port=port, user=user, password=password)
cursor = connection.cursor()

graph_query = """
SELECT * FROM SPARQL_TABLE('
  SELECT ?s ?p ?o 
  WHERE { GRAPH <ukraine_knowledgegraph> { ?s ?p ?o . } }
');
"""

cursor.execute(graph_query)
graph_rows = cursor.fetchall()

cursor.close()
connection.close()

import pandas as pd
graph_df = pd.DataFrame(graph_rows, columns=['subject', 'predicate', 'object'])
graph_df.head()

,subject,predicate,object
0,C1,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,Country
1,C2,http://www.w3.org/1999/02/22-rdf-syntax-ns#type,Country
2,C1,name,Ukraine
3,C2,name,Russia
4,Force_Multinational_Peacekeeping_Ukraine,name,Multinational peacekeeping force for Ukraine

In [36]:
from langchain_hana import HanaRdfGraph

connection = dbapi.connect(address=address, port=port, user=user, password=password)

graph_uri = "ukraine_knowledgegraph"
graph = HanaRdfGraph(
    graph_uri=graph_uri,
    connection = connection,
    auto_extract_ontology = True
)

print(graph.get_schema.serialize(format='turtle'))

@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/estimates> a owl:ObjectProperty ;
    rdfs:label "estimates" ;
    rdfs:domain <file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/Country> ;
    rdfs:range xsd:uri .

<file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/name> a owl:DatatypeProperty ;
    rdfs:label "name" ;
    rdfs:domain <file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/Country> ;
    rdfs:range xsd:string .

<file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/uses> a owl:ObjectProperty ;
    rdfs:label "uses" ;
    rdfs:domain <file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/Country> ;
    rdfs:range xsd:uri .

<file:///c:/Users/I745534/OneDrive%20-%20SAP%20SE/Documents/Daedalus%20Alpha/DEIG/Hackathon/3%20Oslo/ai_hackathon_oslo/ukraine/Country> a owl:Class ;
    rdfs:label "Country" .

In [37]:
from langchain_hana import HanaSparqlQAChain
from gen_ai_hub.proxy.langchain.init_models import init_llm

model_to_use = "gpt-5"
llm = init_llm(model_name=model_to_use)

from langchain_core.prompts import PromptTemplate

SPARQL_GENERATION_SELECT_TEMPLATE = PromptTemplate(
    input_variables=["schema", "prompt"], 
    template="""You are an expert in SPARQL queries. Given the following RDF schema and a user question, generate a SPARQL SELECT query to retrieve relevant information.

Schema:
{schema}

User Question: {prompt}

Generate ONLY a SPARQL SELECT query (no explanations, no markdown). The query must include a WHERE clause.
Example format:
SELECT ?subject ?predicate ?object
WHERE {{
    ?subject ?predicate ?object .
    FILTER(...)
}}
"""
)

SPARQL_QA_TEMPLATE = PromptTemplate(
    input_variables=["context", "prompt"], 
    template="""Based on the following information from a knowledge graph, provide a comprehensive answer to the user's question.

User Question: {prompt}

Knowledge Graph Data:
{context}

Provide a clear, detailed summary based on this data. If the data is empty or doesn't contain relevant information, state that clearly.
"""
)

In [38]:
from typing import cast

chain = HanaSparqlQAChain.from_llm(
    llm=llm,
    verbose=True,
    allow_dangerous_requests=True,
    graph=graph,
    sparql_generation_prompt=cast(PromptTemplate, SPARQL_GENERATION_SELECT_TEMPLATE),
    qa_prompt=cast(PromptTemplate, SPARQL_QA_TEMPLATE)
)

chain.invoke({"query": "Give me all triples related to Ukraine."})

> Entering new HanaSparqlQAChain chain...

AttributeError: 'RunnableSequence' object has no attribute 'output_key'